replicaCount: 1
terminationGracePeriodSeconds: 18000

livekit:
  log_level: info
  rtc:
    use_external_ip: true
    port_range_start: 50000
    port_range_end: 60000
    tcp_port: 7881
  redis:
    address: 
  keys:


loadBalancer:
  type: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts:
        - livekit.beta.numerique.gouv.fr
      secretName: livekit-dinum-cert

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

nodeSelector: {}
resources: {}
