{{- if or (not .Values.app.config.djangoSuperuserEmail) (not .Values.app.config.djangoSuperuserUsername) (not .Values.app.config.djangoSuperuserPassword) (not .Values.app.config.secretKey) }}
{{- $secretName := printf "%s-%s" (include "helper.fullname" .) "admin" }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $secretName }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "admin")) | nindent 4 }}
data:
  {{- if not .Values.app.config.djangoSuperuserEmail }}
  {{- if and $existing.data $existing.data.DJANGO_SUPERUSER_EMAIL }}
  DJANGO_SUPERUSER_EMAIL: {{ $existing.data.DJANGO_SUPERUSER_EMAIL | quote }}
  {{- else }}
  DJANGO_SUPERUSER_EMAIL: {{ (printf "%s@domain.local" (.Values.app.config.djangoSuperuserUsername | default "admin")) | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if not .Values.app.config.djangoSuperuserUsername }}
  {{- if and $existing.data $existing.data.DJANGO_SUPERUSER_USERNAME }}
  DJANGO_SUPERUSER_USERNAME: {{ $existing.data.DJANGO_SUPERUSER_USERNAME | quote }}
  {{- else }}
  DJANGO_SUPERUSER_USERNAME: {{ "admin" | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if not .Values.app.config.djangoSuperuserPassword }}
  {{- if and $existing.data $existing.data.DJANGO_SUPERUSER_PASSWORD }}
  DJANGO_SUPERUSER_PASSWORD: {{ $existing.data.DJANGO_SUPERUSER_PASSWORD | quote }}
  {{- else }}
  DJANGO_SUPERUSER_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if not .Values.app.config.secretKey }}
  {{- if and $existing.data $existing.data.SECRET_KEY }}
  SECRET_KEY: {{ $existing.data.SECRET_KEY | quote }}
  {{- else }}
  SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
