apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "app" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "app")) | nindent 4 }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.app.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "app") | nindent 6 }}
  strategy:
    type: {{ .Values.app.strategy.type }}
    {{- if eq .Values.app.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.app.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.app.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      {{- if or .Values.app.podAnnotations .Values.app.secrets .Values.app.env  }}
      annotations:
        {{- include "helper.checksum" (list $ "/app/configmap.yaml") | nindent 8 }}
        {{- include "helper.checksum" (list $ "/app/secret.yaml") | nindent 8 }}
        {{- if .Values.app.podAnnotations }}
        {{- toYaml .Values.app.podAnnotations | nindent 8 }}
        {{- end }}
      {{- end }}
      labels: {{- include "helper.labels" (dict "root" . "componentName" "app") | nindent 8 }}
        {{- if .Values.app.podLabels }}
        {{- toYaml .Values.app.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.app.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.app.imagePullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if (get .Values "app").serviceAccount.enabled }}
      serviceAccountName: {{ .Values.app.serviceAccount.name | default (printf "%s-%s" (include "helper.fullname" .) "app") }}
      {{- end }}
      {{- if .Values.app.podSecurityContext }}
      securityContext: {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.app.initContainers }}
      initContainers: {{- tpl (toYaml .Values.app.initContainers) . | nindent 6 }}
      {{- end }}
      containers:
      - name: app
        {{- if .Values.app.securityContext }}
        securityContext: {{- toYaml .Values.app.securityContext | nindent 10 }}
        {{- end }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        {{- if .Values.app.command }}
        command:
        {{- range .Values.app.command }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.app.args }}
        args:
        {{- range .Values.app.args }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.app.containerPort }}
          protocol: TCP
        {{- if .Values.app.extraPorts }}
          {{- toYaml .Values.app.extraPorts | nindent 8 }}
        {{- end }}
        env:
        {{- (include "helper.config" .) | nindent 8 }}
        {{- if or .Values.app.env .Values.app.secrets .Values.app.envFrom }}
        envFrom:
        {{- if .Values.app.env }}
        - configMapRef:
            name: {{ printf "%s-%s" (include "helper.fullname" .) "app" }}
        {{- end }}
        {{- if .Values.app.secrets }}
        - secretRef:
            name: {{ printf "%s-%s" (include "helper.fullname" .) "app" }}
        {{- end }}
        {{- if .Values.app.envFrom }}
          {{- toYaml .Values.app.envFrom | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.app.probes.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: {{ .Values.app.probes.healthcheck.path }}
            port: {{ .Values.app.probes.healthcheck.port | default .Values.app.containerPort }}
          initialDelaySeconds: {{ .Values.app.probes.startupProbe.initialDelaySeconds }}
          successThreshold: {{ .Values.app.probes.startupProbe.successThreshold }}
          failureThreshold: {{ .Values.app.probes.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.app.probes.startupProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.app.probes.startupProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.app.probes.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.app.probes.healthcheck.path }}
            port: {{ .Values.app.probes.healthcheck.port | default .Values.app.containerPort }}
          initialDelaySeconds: {{ .Values.app.probes.readinessProbe.initialDelaySeconds }}
          successThreshold: {{ .Values.app.probes.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.app.probes.readinessProbe.failureThreshold }}
          periodSeconds: {{ .Values.app.probes.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.app.probes.readinessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.app.probes.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.app.probes.healthcheck.path }}
            port: {{ .Values.app.probes.healthcheck.port | default .Values.app.containerPort }}
          initialDelaySeconds: {{ .Values.app.probes.livenessProbe.initialDelaySeconds }}
          successThreshold: {{ .Values.app.probes.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.app.probes.livenessProbe.failureThreshold }}
          periodSeconds: {{ .Values.app.probes.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.app.probes.livenessProbe.timeoutSeconds }}
        {{- end }}
        resources: {{- toYaml .Values.app.resources | nindent 10 }}
        {{- if .Values.app.volumeMounts }}
        volumeMounts: {{- toYaml .Values.app.volumeMounts | nindent 8 }}
        {{- end }}
      {{- if .Values.app.extraContainers }}
        {{- tpl (toYaml .Values.app.extraContainers) . | nindent 6 }}
      {{- end }}
      {{- if .Values.app.hostAliases }}
      hostAliases: {{- toYaml .Values.app.hostAliases | nindent 6 }}
      {{- end }}
      {{- if .Values.app.nodeSelector }}
      nodeSelector: {{- toYaml .Values.app.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.app.affinity }}
      affinity: {{- toYaml .Values.app.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.app.tolerations }}
      tolerations: {{- toYaml .Values.app.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.app.volumes }}
      volumes: {{- toYaml .Values.app.volumes | nindent 6 }}
      {{- end }}
