{{- range .Values.app.imagePullSecrets }}
{{- if and .create .username .password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | default (printf "%s-%s-%s" (include "helper.fullname" $) "app" "pullsecret") }}
  labels: {{- (include "helper.labels" (dict "root" $ "componentName" "app")) | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "helper.imagePullSecret" dict "username" .username "password" .password "email" .email "registry" .registry }}
{{- end }}
{{- end }}
