{{- if and .Values.app.serviceAccount.enabled .Values.app.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.serviceAccount.name | default (printf "%s-%s" (include "helper.fullname" .) "app") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "app")) | nindent 4 }}
  {{- if .Values.app.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml .Values.app.serviceAccount.annotations) . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.app.serviceAccount.automountServiceAccountToken }}
{{- end }}
