{{- range .Values.imagePullSecrets }}
{{- if and .create .username .password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | default (printf "%s-%s" (include "helper.fullname" $) "pullsecret") }}
  labels: {{- include "helper.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "helper.imagePullSecret" dict "username" .username "password" .password "email" .email "registry" .registry }}
{{- end }}
{{- end }}
