{{- if .Values.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "helper.fullname" . }}
  labels: {{- include "helper.labels" . | nindent 4 }}
data:
  {{- if .Values.secrets -}}
  {{- include "helper.secret" .Values | indent 2 }}
  {{- end -}}
{{- end -}}
