apiVersion: v1
kind: Service
metadata:
  name: {{ include "helper.fullname" . }}
  labels: {{- include "helper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
    protocol: {{ .Values.service.protocol | default "TCP" }}
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    name: {{ .Values.service.portName | default "http" }}
  {{- if .Values.service.extraPorts -}}
  {{- toYaml .Values.service.extraPorts | nindent 2 -}}
  {{- end }}
  selector: {{- include "helper.selectorLabels" . | nindent 4 }}
