http:
  middlewares:
    no-x-fwd-user-header:
      headers:
        customRequestHeaders:
          X-Forwarded-User: ""
  routers:
    default:
      middlewares:
      - no-x-fwd-user-header
      rule: Host(`grist.docker.localhost`)
      service: default
    dw-0:
      middlewares:
      - no-x-fwd-user-header
      rule: Host(`grist.docker.localhost`) && PathPrefix(`/dw/dw-0`)
      service: dw-0
    dw-1:
      middlewares:
      - no-x-fwd-user-header
      rule: Host(`grist.docker.localhost`) && PathPrefix(`/dw/dw-1`)
      service: dw-1
    dw-2:
      middlewares:
      - no-x-fwd-user-header
      rule: Host(`grist.docker.localhost`) && PathPrefix(`/dw/dw-2`)
      service: dw-2
  services:
    default:
      loadBalancer:
        servers:
        - url: http://grist:8484
    dw-0:
      loadBalancer:
        servers:
        - url: http://grist-dw-0:8484
    dw-1:
      loadBalancer:
        servers:
        - url: http://grist-dw-1:8484
    dw-2:
      loadBalancer:
        servers:
        - url: http://grist-dw-2:8484
