{{- $envVars := include "plane.common.env" (list . .Values.web) -}}
{{- $fullName := include "plane.web.fullname" . -}}
{{- $component := "web" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "plane.common.labels" (list . $component) | nindent 4 }}
  annotations:
    {{- toYaml $.Values.web.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "plane.common.selectorLabels" (list . $component) | nindent 4 }}
