{{- if .Values.cnpgCluster.enabled -}}
{{- $dbHost := printf "%s-%s" .Values.cnpgCluster.fullnameOverride "rw" -}}
{{- $dbPort := 5432 -}}
{{- $dbName := .Values.cnpgCluster.cluster.initdb.database -}}
{{- $dbUser := (get (get (lookup "v1" "Secret" .Release.Namespace .Values.cnpgCluster.cluster.initdb.secret.name) "data" | default dict) "username" | b64dec) | default .Values.cnpgCluster.cluster.initdb.owner -}}
{{- $dbPass := (get (get (lookup "v1" "Secret" .Release.Namespace .Values.cnpgCluster.cluster.initdb.secret.name) "data" | default dict) "password" | b64dec) | default (randAlphaNum 24) -}}
{{- $dbAdminUser := (get (get (lookup "v1" "Secret" .Release.Namespace .Values.cnpgCluster.cluster.superuserSecret) "data" | default dict) "username" | b64dec) | default "postgres" -}}
{{- $dbAdminPass := (get (get (lookup "v1" "Secret" .Release.Namespace .Values.cnpgCluster.cluster.superuserSecret) "data" | default dict) "password" | b64dec) | default (randAlphaNum 24) -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" .Values.cnpgCluster.fullnameOverride "admin" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "postgresql")) | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ $dbAdminUser | b64enc | quote }}
  password: {{ $dbAdminPass | b64enc | quote }}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" .Values.cnpgCluster.fullnameOverride "app" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "postgresql")) | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ $dbUser | b64enc | quote }}
  password: {{ $dbPass | b64enc | quote }}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" .Values.cnpgCluster.fullnameOverride "infos" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "postgresql")) | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" $dbUser $dbPass $dbHost $dbPort $dbName | b64enc | quote }}
  DATABASE_HOST: {{ $dbHost | b64enc | quote }}
  DATABASE_PORT: {{ $dbPort | toString | b64enc | quote }}
  DATABASE_NAME: {{ $dbName | b64enc | quote }}
  DATABASE_USERNAME: {{ $dbUser | b64enc | quote }}
  DATABASE_PASSWORD: {{ $dbPass | b64enc | quote }}
{{- end -}}
