{{- $component := "lb" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grist.lb.fullname" . }}
  labels:
    {{- include "grist.common.labels" (list . $component) | nindent 4 }}
  annotations:
    {{- toYaml .Values.loadBalancer.service.annotations | nindent 4 }}
spec:
  type: {{ $.Values.loadBalancer.service.type }}
  ports:
    - port: {{ $.Values.loadBalancer.service.port }}
      targetPort: {{ $.Values.loadBalancer.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "grist.common.selectorLabels" (list . $component) | nindent 4 }}
