{{- if .Values.docWorkerSurboost.enabled }}
{{- $envVars := include "grist.common.env" (list . .Values.docWorkerSurboost) -}}
{{- $fullName := printf "%s-surboost" (include "grist.doc.fullname" .) -}}
{{- $component := "doc-worker-surboost" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "grist.common.labels" (list . $component) | nindent 4 }}
spec:
  replicas: {{ .Values.docWorkerSurboost.replicas }}
  selector:
    matchLabels:
      {{- include "grist.common.selectorLabels" (list . $component) | nindent 6 }}
  {{- with .Values.docWorkerSurboost.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        fileChecksum: {{ include (print $.Template.BasePath "/file_cm.yaml") . | sha256sum }}
        {{- with .Values.docWorkerSurboost.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "grist.common.selectorLabels" (list . $component) | nindent 8 }}
        app.kubernetes.io/part-of: doc-worker-pool
    spec:
      {{- with .Values.docWorkerSurboost.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $.Values.image.credentials }}
      imagePullSecrets:
        - name: {{ include "grist.secret.dockerconfigjson.name" (dict "fullname" (include "grist.fullname" .) "imageCredentials" $.Values.image.credentials) }}
      {{- end}}
      shareProcessNamespace: {{ .Values.docWorkerSurboost.shareProcessNamespace }}
      containers:
        {{- with .Values.docWorkerSurboost.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ (.Values.docWorkerSurboost.image | default dict).repository | default .Values.image.repository }}:{{ (.Values.docWorkerSurboost.image | default dict).tag | default .Values.image.tag }}"
          imagePullPolicy: {{ (.Values.docWorkerSurboost.image | default dict).pullPolicy | default .Values.image.pullPolicy }}
          {{- with .Values.docWorkerSurboost.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.docWorkerSurboost.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: INTERNAL_LB
              value: {{ include "grist.lb.fullname" . }}
            {{- if $envVars}}
            {{- $envVars | indent 12 }}
            {{- end }}
          {{- with .Values.docWorkerSurboost.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.docWorkerSurboost.service.targetPort }}
              protocol: TCP
          {{- if .Values.docWorkerSurboost.probes.liveness }}
          livenessProbe:
            {{- include "grist.probes.abstract" (merge .Values.docWorkerSurboost.probes.liveness (dict "targetPort" .Values.docWorkerSurboost.service.targetPort )) | nindent 12 }}
          {{- end }}
          {{- if .Values.docWorkerSurboost.probes.readiness }}
          readinessProbe:
            {{- include "grist.probes.abstract" (merge .Values.docWorkerSurboost.probes.readiness (dict "targetPort" .Values.docWorkerSurboost.service.targetPort )) | nindent 12 }}
          {{- end }}
          {{- if .Values.docWorkerSurboost.probes.startup }}
          startupProbe:
            {{- include "grist.probes.abstract" (merge .Values.docWorkerSurboost.probes.startup (dict "targetPort" .Values.docWorkerSurboost.service.targetPort )) | nindent 12 }}
          {{- end }}
          {{- with .Values.docWorkerSurboost.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.docWorkerSurboost.useVolume.enabled }}
            - name: persist
              mountPath: /persist
            {{- end }}
            {{- range $index, $value := .Values.mountFiles }}
            - name: "files-{{ $index }}"
              mountPath: {{ $value.path }}
              subPath: content
            {{- end }}
            {{- range $name, $volume := .Values.docWorkerSurboost.persistence }}
            - name: "{{ $name }}"
              mountPath: "{{ $volume.mountPath }}"
            {{- end }}
            {{- if .Values.docWorkerSurboost.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.docWorkerSurboost.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
      {{- with .Values.docWorkerSurboost.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.docWorkerSurboost.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.docWorkerSurboost.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- range $index, $value := .Values.mountFiles }}
        - name: "files-{{ $index }}"
          configMap:
            name: "{{ include "grist.fullname" $ }}-files-{{ $index }}"
        {{- end }}
        {{- range $name, $volume := .Values.docWorkerSurboost.persistence }}
        - name: "{{ $name }}"
          {{- if eq $volume.type "emptyDir" }}
          emptyDir: {}
          {{- else }}
          persistentVolumeClaim:
            claimName: "{{ $fullName }}-{{ $name }}"
          {{- end }}
        {{- end }}
        {{- if .Values.docWorkerSurboost.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.docWorkerSurboost.extraVolumes  "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.docWorkerSurboost.useVolume.enabled }}
        - name: persist
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: ephemeral
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: {{ .Values.docWorkerSurboost.useVolume.storageClassName }}
                resources:
                  requests:
                    storage: {{ .Values.docWorkerSurboost.useVolume.storageSize }}
        {{- end }}
{{- end }}
